Algoritmo "Exibir Mensagem"
// Disciplina   : [Interfaces e JavaScript]
// Professor   : Jailson Santos
// Descrição   : Exibe uma mensagem
// Autor(a)    : Luís Gabriel da Silva
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis
 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
// "Escreva" exibe uma mensagem na tela, e "Escreval" pula uma linha
Escreval ("Teste")
Escreval ("PROA")
Escreva("Equipe 04")
Fimalgoritmo